# -*- coding: utf-8 -*-
"""Credit Card Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQrMrM8k_7o_x0zfbec2Ny8WEfA07ldF

**IMPORT DATA**
"""

#import data
from google.colab import files
files.upload()

import pandas as pd
data=pd.read_csv('CC_GENERAL.csv')
data

"""**UNDERSTANDING & HANDLING DATA**"""

#missing value
data.isnull().sum()

#duplikasi data
data.duplicated().sum()

#hapus missing value
data.dropna(inplace=True)

data.isnull().sum()

#statistika deskriptif
data.describe()

#remove CUST_ID variable
data1=data.drop(columns='CUST_ID',axis=1)
data1

#Heatmap korelasi
import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(10,10))
sns.heatmap(data1.corr(),annot=True, fmt=".2f", cmap="coolwarm")
plt.show()

#detect outlier
import seaborn as sns
import matplotlib.pyplot as plt
for n in data1.columns:
  sns.boxplot(data1[n])
  plt.figure(figsize=(5,5))
  plt.show()

"""**SCALING DATA**"""

#Scaling data karena banyak variabel yang punya outlier
from sklearn.preprocessing import RobustScaler
scaler=RobustScaler()
data_scale=scaler.fit_transform(data1)
data_scale=pd.DataFrame(data_scale,columns=data1.columns)
data_scale

"""**CLUSTERING MODEL**"""

#K-MEANS

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

#mencari K terbaik dengan silhouette score
silhouette_scores= {}
for k in range (2,11):
  km=KMeans(n_clusters=k,random_state=42,init='k-means++')
  km.fit(data_scale)
  label=km.predict(data_scale)
  sc=silhouette_score(data_scale,label)
  silhouette_scores[k] = sc
  print(f"Cluster {k} → Silhouette Score: {sc:.3f}")

#plot silhouette score
plt.figure(figsize=(10, 4))
plt.plot(list(silhouette_scores.keys()), list(silhouette_scores.values()), marker='o', color='green')
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Silhouette Score")
plt.title("K-Means - Silhouette Score")
plt.show()

#MINI BATCH K-MEANS

from sklearn.cluster import MiniBatchKMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

#mencari K terbaik dengan silhouette score
silhouette_scores= {}
for k in range (2,11):
  mbk=MiniBatchKMeans(n_clusters=k,random_state=42,init='k-means++')
  mbk.fit(data_scale)
  label=mbk.predict(data_scale)
  sc=silhouette_score(data_scale,label)
  silhouette_scores[k] = sc
  print(f"Cluster {k} → Silhouette Score: {sc:.3f}")

#plot silhouette score
plt.figure(figsize=(10, 4))
plt.plot(list(silhouette_scores.keys()), list(silhouette_scores.values()), marker='o', color='green')
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Silhouette Score")
plt.title("Mini Batch K-Means - Silhouette Score")
plt.show()

#BISECTING K-MEANS

from sklearn.cluster import BisectingKMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

#mencari K terbaik dengan silhouette score

silhouette_scores={}
for k in range (2,11):
  bk=BisectingKMeans(n_clusters=k,random_state=42,init='k-means++')
  bk.fit(data_scale)
  label=bk.predict(data_scale)
  sc=silhouette_score(data_scale,label)
  silhouette_scores[k] = sc
  print(f"Cluster {k} → Silhouette Score: {sc:.3f}")

#plot silhouette score
plt.figure(figsize=(10, 4))
plt.plot(list(silhouette_scores.keys()), list(silhouette_scores.values()), marker='o', color='green')
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Silhouette Score")
plt.title("Bisecting K-Means - Silhouette Score")
plt.show()

!pip install fuzzy-c-means

!pip install scikit-fuzzy

!pip install -U scikit-fuzzy

#FUZZY C MEANS

from fcmeans import FCM
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

#mencari K terbaik dengan silhouette score
silhouette_scores= {}
for k in range (2,11):
  fcm=FCM(n_clusters=k,random_state=42)
  fcm.fit(data_scale.values)
  label=fcm.predict(data_scale.values)
  sc=silhouette_score(data_scale,label)
  silhouette_scores[k] = sc
  print(f"Cluster {k} → Silhouette Score: {sc:.3f}")

#plot silhouette score
plt.figure(figsize=(10, 4))
plt.plot(list(silhouette_scores.keys()), list(silhouette_scores.values()), marker='o', color='green')
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Silhouette Score")
plt.title("Fuzzy C Means - Silhouette Score")
plt.show()

"""model dan n cluster dengan silhouette score terbaik adalah K-Means dengan k=2 dan Bisecting K-Means dengan k=2

**PELABELAN DAN KARAKTERISTIK SETIAP KLASTER**

**K-MEANS**
"""

#Karakteristik
n=2
km=KMeans(n_clusters=n,random_state=42,init='k-means++')
label_km=km.fit_predict(data_scale)
all_data_cluster= data1.copy()
all_data_cluster['Kelas'] = label_km
cluster_avg= all_data_cluster.groupby('Kelas').mean()
display(cluster_avg.T)

#plot
import matplotlib.pyplot as plt
import seaborn as sns

# daftar variabel yang mau diplot (13 variabel)
variabel=data1.columns.tolist()

#plot 5 baris × 3 kolom
fig, axes = plt.subplots(nrows=6, ncols=3, figsize=(18, 20))
axes = axes.flatten()

for i, var in enumerate(variabel):
    ax = axes[i]
    sns.barplot(x=cluster_avg.index, y=cluster_avg[var], ax=ax)
    ax.set_title(f'{var} by Cluster')
    ax.set_xlabel('Cluster')
    ax.set_ylabel(var)

# sisanya dikosongkan kalau plot tidak penuh sampai 18 slot
for j in range(len(variabel), 18):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

#Pelabelan
pelabelan=data.iloc[:,[0]]
pelabelan['Kelas']=label_km
pelabelan['Karakter Customer']=pelabelan['Kelas'].replace([0,1],['High value customer','Low value customer'])
pelabelan

#Proporsi kelas
import numpy as np

counts = pelabelan['Kelas'].value_counts().sort_index()
value = counts.values
label= {
    0: 'High value customer',
    1: 'Low value customer'}

plt.figure(figsize=(7, 7))
plt.pie(
    counts,
    labels=[label[i] for i in counts.index],
    autopct=lambda pct: f"{pct:.1f}%\n({int(round(pct/100*np.sum(value1)))})",
    wedgeprops=dict(width=0.55))

plt.title('Distribusi Cluster K-Means k=2')
plt.show()

"""**BISECTING K-MEANS**"""

#Karakteristik
n=2
bk=BisectingKMeans(n_clusters=n,random_state=42,init='k-means++')
label_bk=bk.fit_predict(data_scale)
all_data_cluster1= data1.copy()
all_data_cluster1['Kelas'] = label_bk
cluster_avg1= all_data_cluster1.groupby('Kelas').mean()
display(cluster_avg1.T)

#plot
import matplotlib.pyplot as plt
import seaborn as sns

# daftar variabel yang mau diplot (13 variabel)
variabel1=data1.columns.tolist()

#plot 5 baris × 3 kolom
fig, axes = plt.subplots(nrows=6, ncols=3, figsize=(18, 20))
axes = axes.flatten()

for i, var in enumerate(variabel1):
    ax = axes[i]
    sns.barplot(x=cluster_avg1.index, y=cluster_avg1[var], ax=ax)
    ax.set_title(f'{var} by Cluster')
    ax.set_xlabel('Cluster')
    ax.set_ylabel(var)

# sisanya dikosongkan kalau plot tidak penuh sampai 18 slot
for j in range(len(variabel1), 18):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

#Pelabelan
pelabelan1=data.iloc[:,[0]]
pelabelan1['Kelas']=label_bk
pelabelan1['Karakter Customer']=pelabelan1['Kelas'].replace([0,1],['High value customer','Low value customer'])
pelabelan1

#Proporsi kelas
import numpy as np

counts1= pelabelan1['Kelas'].value_counts().sort_index()
value1= counts1.values
label1= {
    0: 'High value customer',
    1: 'Low value customer'}

plt.figure(figsize=(7, 7))
plt.pie(
    counts1,
    labels=[label1[i] for i in counts1.index],
    autopct=lambda pct: f"{pct:.1f}%\n({int(round(pct/100*np.sum(value1)))})",
    wedgeprops=dict(width=0.55)
)

plt.title('Distribusi Cluster Bisecting K-Means k=2')
plt.show()